"""adjust_lead_and_industry_table

Revision ID: 5cb9b07fcbd5
Revises: 65c753e7535c
Create Date: 2026-01-30 19:05:33.141723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cb9b07fcbd5'
down_revision: Union[str, Sequence[str], None] = '65c753e7535c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
