"""create_industry_table

Revision ID: 65c753e7535c
Revises: 2bb67eba442b
Create Date: 2026-01-30 16:11:08.606149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c753e7535c'
down_revision: Union[str, Sequence[str], None] = '2bb67eba442b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='NOW()', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default='NOW()', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industries_id'), 'industries', ['id'], unique=False)
    op.create_index(op.f('ix_industries_name'), 'industries', ['name'], unique=True)
    op.add_column('leads', sa.Column('industry_id', sa.Integer(), nullable=False))
    op.add_column('leads', sa.Column('created_at', sa.DateTime(), server_default='NOW()', nullable=False))
    op.add_column('leads', sa.Column('updated_at', sa.DateTime(), server_default='NOW()', nullable=False))
    op.create_foreign_key(None, 'leads', 'industries', ['industry_id'], ['id'])
    op.drop_column('leads', 'industry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('industry', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'leads', type_='foreignkey')
    op.drop_column('leads', 'updated_at')
    op.drop_column('leads', 'created_at')
    op.drop_column('leads', 'industry_id')
    op.drop_index(op.f('ix_industries_name'), table_name='industries')
    op.drop_index(op.f('ix_industries_id'), table_name='industries')
    op.drop_table('industries')
    # ### end Alembic commands ###
